buildVariable: false
familyName: Noto Sans Anatolian Hieroglyphs
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSansAnatolianHieroglyphs.designspace
